#@ load("_grafana-cloud-config.lib.yml", "remote_write")

remote_write: #@ remote_write()

global:
  scrape_interval: 15s

scrape_configs:
- job_name: node
  static_configs:
    - targets: ['localhost:9100']
      labels:
        group: gke-node
        cluster-instance: __meta_gce_private_ip

