apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k6-loadgen
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6-loadgen
            image: loadimpact/k6
            command: ["k6", "run", "https://raw.githubusercontent.com/cfossguy/grafana-labs-sandbox/main/k6/script.js"]
          restartPolicy: Never
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k6-errorgen
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6-errorgen
            image: loadimpact/k6
            command: ["k6", "run", "https://raw.githubusercontent.com/cfossguy/grafana-labs-sandbox/main/k6/error-script.js"]
          restartPolicy: Never
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k6-spikegen
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6-spikegen
            image: loadimpact/k6
            command: ["k6", "run", "https://raw.githubusercontent.com/cfossguy/grafana-labs-sandbox/main/k6/spike-script.js"]
          restartPolicy: Never