apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k6-loadgen
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6-loadgen
            image: loadimpact/k6
            command: ["k6", "run", "https://raw.githubusercontent.com/cfossguy/grafana-labs-sandbox/main/k6/script.js"]
          restartPolicy: Never