{
 "title": "Mongo Movie",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "_movie_year",
    "label": "Movie",
    "query": {
     "query": "sample_mflix.movies.aggregate([\n    {\"$match\": {year: {\"$gt\": 2011}}},\n    {\"$project\": {_id: 0, movie_year: {\"$concat\": [\"$title\", \" - \", {\"$toString\":\"$year\"}]}}} \n])"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "canvas",
   "gridPos": { "h": 19, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "sample_mflix.movies.find({\"title\":\"$_movie\", year: $_year}, {title: 1, _id: 0, poster: 1})"
    }
   ]
  },
  {
   "title": "Plot",
   "type": "table",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "query": "sample_mflix.movies.find({\"title\":\"$_movie\", year: $_year}, {plot: 1, _id: 0})"
    }
   ]
  },
  {
   "title": "Awards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "sample_mflix.movies.find({title: \"$_movie\", year: $_year}, {\"awards\":1})"
    }
   ]
  },
  {
   "title": "IMDB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "sample_mflix.movies.find({title: \"$_movie\", year: $_year}, {\"imdb.rating\": 1, \"imdb.votes\": 1})"
    }
   ]
  },
  {
   "title": "Tomatoes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "sample_mflix.movies.find({title: \"$_movie\", year: $_year}, {tomatoes: 1})"
    }
   ]
  },
  {
   "title": "Cast",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 14 },
   "targets": [
    {
     "query": "sample_mflix.movies.aggregate([\n    { \"$match\": {title: \"$_movie\", year: $_year}},\n    { \"$project\" : {\"cast\": 1, \"_id\": 0}},\n    { \"$unwind\" : \"$cast\"}]\n)"
    }
   ]
  },
  {
   "title": "Directors",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 14 },
   "targets": [
    {
     "query": "sample_mflix.movies.aggregate([\n    { \"$match\": {title: \"$_movie\", year: $_year}},\n    { \"$project\" : {\"directors\": 1, \"_id\": 0}},\n    { \"$unwind\" : \"$directors\"}]\n)"
    }
   ]
  },
  {
   "title": "Writers",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 14 },
   "targets": [
    {
     "query": "sample_mflix.movies.aggregate([\n    { \"$match\": {title: \"$_movie\", year: $_year}},\n    { \"$project\" : {\"writers\": 1, \"_id\": 0}},\n    { \"$unwind\" : \"$writers\"}]\n)"
    }
   ]
  },
  {
   "title": "Tomato Meter",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "sample_mflix.movies.find({\"title\":\"$_movie\", year: $_year}, {\"tomatoes.viewer.meter\": 1})"
    }
   ]
  },
  {
   "title": "Critics Consensus",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 18 },
   "targets": [
    {
     "query": "sample_mflix.movies.find({\"title\":\"$_movie\", year: $_year}, {\"tomatoes.consensus\": 1, _id: 0})"
    }
   ]
  }
 ]
}