{
 "title": "Log Demo - Legacy Tomcat App",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "logs_datasource", "label": "Logs Datasource", "query": "loki" },
   { "name": "metrics_datasource", "label": "Metrics Data Source", "query": "prometheus" },
   { "name": "application", "label": "Application", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "Summary - Prometheus(Metrics) + Loki(Logs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Prometheus: Free Memory (GB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{app=\"$application\"} - node_memory_MemFree_bytes{app=\"$application\"}) / 1e+9"
    }
   ]
  },
  {
   "title": "Prometheus: Free Disk",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(1 -   (    max without (mountpoint, fstype) (node_filesystem_avail_bytes{app=\"$application\"})    /    max without (mountpoint, fstype) (node_filesystem_size_bytes{app=\"$application\", fstype!=\"\"})   ) > .001 ) * 100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Loki: Info Message Count ",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum by(msg) (count_over_time({app=\"tomcat_app\"} | \n    pattern \"<_> <_> <level> <_> <class> <_> <_> <_> <log_id> <_> <msg>\" | level=\"INFO\" [$__range])) ",
     "legendFormat": "{{msg}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Prometheus: CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "100 - (avg by (app) (rate(node_cpu_seconds_total{app=\"$application\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Loki: Log Count By Level",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({app=\"tomcat_app\"} | \n    pattern \"<_> <_> <level> <_> <class> <_> <_> <_> <log_id> <_> <msg>\"[$__range])) ",
     "legendFormat": "{{level}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Loki: Log Stream",
   "type": "logs",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"tomcat_app\"} | pattern \"<_> <_> <level> <_> <class> <_> <_> <_> <log_id> <_> <msg>\""
    }
   ]
  },
  {
   "title": "Prometheus: Network Traffic - KB(s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(sum by(app) (rate(node_network_transmit_bytes_total{app=\"$application\"}[1m])) + sum by(app) (rate(node_network_receive_bytes_total{app=\"$application\"}[1m]))) / 1000",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Infrastructure - USE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  },
  {
   "title": "Prometheus: CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{app=\"tomcat_app\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Prometheus: CPU Saturation (Load1 per CPU)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_load1_per_cpu:ratio{app=\"tomcat_app\"} ",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "Prometheus: Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{app=\"tomcat_app\"}",
     "legendFormat": "memory utilisation ratio"
    }
   ]
  },
  {
   "title": "Prometheus: Memory Saturation (Major Page Faults)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_vmstat_pgmajfault:rate5m{app=\"tomcat_app\"} ",
     "legendFormat": "Major page Faults"
    }
   ]
  },
  {
   "title": "Prometheus: Network Utilisation (Bytes Receive/Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate5m{app=\"tomcat_app\"} != 0",
     "legendFormat": "Receive"
    },
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate5m{app=\"tomcat_app\"} != 0",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Prometheus: Network Saturation (Drops Receive/Transmit)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_network_receive_drop_excluding_lo:rate5m{app=\"tomcat_app\"} ",
     "legendFormat": "Receive"
    },
    {
     "expr": "instance:node_network_transmit_drop_excluding_lo:rate5m{app=\"tomcat_app\"}",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Prometheus: Disk IO Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_seconds:rate5m{app=\"tomcat_app\"} != 0",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Prometheus:Disk IO Saturation",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_weighted_seconds:rate5m{app=\"tomcat_app\"} ",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}