#! shared functionality can be extracted into separate files,
#! then loaded in by their function name, especially when functions contain secrets

#! YAML library files must be named *.lib.yml
#@ load("_grafana-cloud-config.lib.yml", "remote_write")

remote_write: #@ remote_write()

rule_files:
  - 'prometheus-rules.yml'

scrape_configs:
  - job_name:       'spring-node'

    scrape_interval: 5s

    metrics_path: '/actuator/prometheus'

    static_configs:
      - targets: [ 'localhost:8082' ]
        labels:
          group: 'production'

      - targets: [ 'localhost:8082' ]
        labels:
          group: 'canary'

