rule_files:
  - 'prometheus-rules.yml'

scrape_configs:
  - job_name:       'spring-node'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    metrics_path: '/actuator/prometheus'

    static_configs:
      - targets: [ 'localhost:8082' ]
        labels:
          group: 'production'

      - targets: [ 'localhost:8082' ]
        labels:
          group: 'canary'

