{
 "title": "Cloud Native Forensics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uri",
    "label": "Spring Boot Endpoints",
    "query": {
     "query": "{job=\"integrations/spring-boot\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"width:100%;height:100px;\">\n  <tr>\n    <td style=\"width:100px; border:1px solid black;\">\n      <img style=\"height:90px;width:90px;\" src=\"https://storage.googleapis.com/se_demo_images/spring-boot.png\"></img>\n    </td>\n    <td style=\"width:100px; border:1px solid black;\">\n      <img style=\"height:90px;width:90px;\" src=\"https://storage.googleapis.com/se_demo_images/k8s.png\"></img>\n    </td>\n    <td style=\"border:1px solid black;\">  \n        <h1>Cloud Native Forensics</h1>\n        <p>Metrics + Logs + Traces</p>\n    </td>\n  </tr>\n</table>\n"
   },
   "targets": [
    { "metricQuery": { "projectName": "solutions-engineering-248511" } }
   ]
  },
  { "title": "Application ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri)(rate(http_server_requests_seconds_sum{endpoint_name=\"spring-node\",uri=~\"[[uri]]\"}[$__interval]))",
     "legendFormat": "{{uri}} "
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri)(rate(http_server_requests_seconds_count{endpoint_name=\"spring-node\",status=\"200\",uri=~\"[[uri]]\"}[1m]))",
     "legendFormat": "{{uri}} "
    }
   ]
  },
  {
   "title": "Error Rate Per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri)(rate(http_server_requests_seconds_count{endpoint_name=\"spring-node\",status!=\"200\",uri=~\"[[uri]]\"}[1m]))",
     "legendFormat": "{{uri}} "
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{app=\"spring-node\",container=\"spring-node\"} |~ `$uri`"
    }
   ]
  },
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "System Load Average",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load_average_1m{endpoint_name=\"spring-node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Live Threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{endpoint_name=\"spring-node\",job=\"integrations/spring-boot\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 25 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count[1m])",
     "legendFormat": "{{instance}} - {{action}} - {{cause}}"
    }
   ]
  }
 ]
}