#copy/pasted from Grafana Enterprise Integrations Management(Kubernetes)
kind: ConfigMap
metadata:
  name: grafana-agent
apiVersion: v1
data:
  agent.yaml: |
    metrics:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 15s
        external_labels:
          cluster: YOUR_CLUSTER_NAME
      configs:
      - name: integrations
        remote_write:
        - url: YOUR_REMOTE_WRITE_URL
          basic_auth:
            username: YOUR_REMOTE_WRITE_USERNAME
            password: YOUR_REMOTE_WRITE_PASSWORD
        scrape_configs:
        - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        - job_name: integrations/spring-boot
          metrics_path: /actuator/prometheus
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [ __meta_kubernetes_endpoints_name ]
              target_label: app
              action: replace
              replacement: $1