apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-node
  name: spring-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-node
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-node
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/solutions-engineering-248511/se-jwilliams-sandbox/spring-node:latest
        imagePullPolicy: Always
        name: spring-node
        ports:
          - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: spring-node
  name: spring-node
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: spring-node
  sessionAffinity: None
  type: LoadBalancer